version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: simple-icons
    versions:
    - 4.10.0
    - 4.11.0
    - 4.13.0
    - 4.14.0
    - 4.15.0
    - 4.17.0
    - 4.20.0
    - 4.9.0
